spring:
  application:
    name: template-service
  cloud:
    gcp:
      storage:
        enabled: false
server:
  error:
    include-message: on_param

storage:
  host: http://localhost:4443
  bucket: sample-bucket
